version: '3.8'

services:

  db:
    image: timescale/timescaledb-ha:pg14-latest
    restart: on-failure
    env_file: ./.env
    environment:
     POSTGRES_USER: $POSTGRESDB_USER
     POSTGRES_PASSWORD: $POSTGRESDB_ROOT_PASSWORD
     POSTGRES_DB: $POSTGRESDB_DATABASE
    ports:
      - 5432:5432
    volumes:
      - ./infrastructure/db/create_db.sql:/docker-entrypoint-initdb.d/create_db.sql
      - db:/var/lib/postgres/data

  sensor-microservice:
    image: sensor-microservice
    container_name: sensor-rest-api-service
    depends_on:
      - db
    build:
      context: .
      dockerfile: Dockerfile
    restart: on-failure
    ports:
      - 8181:8181
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/sensor_rest_app_db

volumes:
  db: