spring:
# Data source
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/sensor_rest_app_db
    username: postgres
    password: PapaEmeritus4_
# Hibernate configuration
  jpa:
    properties:
      hibernate:
        show_sql: true
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/master_changelog.xml
# Swagger configuration
springdoc:
  api-docs:
    path: /api-docs
  override-with-generic-response: false