CREATE TABLE Sensor
(
    id   INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE Measurement
(
    id         INT GENERATED BY DEFAULT AS IDENTITY,
    value      DOUBLE PRECISION NOT NULL,
    raining    boolean          NOT NULL,
    updated_at TIMESTAMP        NOT NULL,
    sensor     VARCHAR(100)     NOT NULL REFERENCES sensor (name),
    PRIMARY KEY (id, updated_at)
);