create table Sensor
(
    id   int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name varchar(100) not null unique
);

create table Measurement
(
    id      int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    value   double precision not null,
    raining boolean          not null,
    sensor  varchar(100)     not null references sensor (name)
);